name: Compile notebooks
on:
  workflow_dispatch:
jobs:
  compile_notebook:
    name: Update plot with new citations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          cache: 'pip'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
          pip install jupyter
      - name: Convert notebook to html
        run: |
          jupyter nbconvert --execute --to html docs/notebook1.ipynb
      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add docs/notebook1.ipynb
          git commit -m "Added html notebook on `date` with GitHub Actions"
          git push origin main --force
