name: Compile notebooks
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  compile_notebook:
    name: Update plot with new citations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install package and Jupyter
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
          pip install jupyter
      - name: Convert notebook to html
        run: |
          jupyter nbconvert --to notebook --execute docs/notebook1.ipynb
          jupyter nbconvert --to html --execute docs/notebook1.ipynb
      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add docs/notebook1.html
          git add docs/notebook1.ipynb
          git commit -m "Added html notebook on `date` with GitHub Actions"
          git push origin main --force
